name = "social-miroir-proxy"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
AIRTABLE_BASE_ID = "appP3oMcKSOcpxj4t"
AIRTABLE_TABLE   = "tblfVEfDgzdLQfuwR"

# Secrets (à définir UNE SEULE FOIS via terminal) :
#   wrangler secret put DISCORD_WEBHOOK
#   wrangler secret put AIRTABLE_TOKEN
